Main/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from allauth.socialaccount.providers.oauth2.urls import default_urlpatterns
from allauth.socialaccount.providers.steam.urls import urlpatterns as steam_urlpatterns
from Providers.Steam.provider import OpenIDProvider

from .views import *

urlpatterns = [
    path('post/', post_index, name="post_index"),
    path("post/<int:pk>/<int:action>/", post_detail, name="post_detail"),
    path("tag/<tag>/", post_tag, name="post_tag"),
    path('', HomePage, name='home'),
    path('signup/', SignUp, name = 'sign_up'),  
    path("search/",SearchResultsView.as_view(), name="search_results"),
    path('search-account/', search_account, name='search_account'),
    path('account_page/<int:user_id>/', user_account, name='user_account'),
    path('my_account/<int:pk>', MyAccountAndUpdateView.as_view(), name='my_account'),
    path('report-post/<int:post_id>/', report_post, name='report_post'),
    path('report-user/<int:user_id>/', report_user, name='report_user'),
    path('get-existing-tags/', get_existing_tags, name='get_existing_tags'),
    path('remove-post/<int:pk>/', remove_post, name='remove_post'),
    path('remove-account/<int:pk>/', remove_account, name='remove_account'),
    path('leagues/', league_list, name='league_list'),
    path('leagues/<int:league_id>/', league_detail, name='league_detail'),
    path('leagues/create/', create_league, name='create_league'),
    path('leagues/<int:league_id>/join/', join_league, name='join_league'),
    path('leagues/<int:league_id>/leave/', leave_league, name='leave_league'),
    path('leagues/<int:league_id>/delete/', delete_league, name='delete_league'),
    path('leagues/<int:league_id>/update/', update_league, name='update_league'),
    path('leagues/<int:league_id>/create_team/', create_team, name='create_team'),
    path('leagues/<int:league_id>/teams/<int:team_id>/', team_detail, name='team_detail'),
    path('leagues/<int:team_id>/edit_team/', edit_team, name='edit_team'),
    path('leagues/<int:team_id>/delete_team/', delete_team, name='delete_team'),
    path('leagues/<int:team_id>/leave_team/', leave_team, name='leave_team'),
    path('leagues/<int:team_id>/join_team/', join_team, name='join_team'),
    path('league/<int:league_id>/create_match/', create_match, name='create_match'),
    path('match/<int:match_id>/edit/', edit_match, name='edit_match'),
    path('match/<int:match_id>/delete/', delete_match, name='delete_match'),
    path('match/<int:match_id>/', match_detail, name='match_detail'),
    path('register-business/',  register_business_number, name='register_business'),
    path('view-discounts/', view_discounts_page, name='discounts'),

    path('notifications/', views.notifications_list, name='notifications_list'),
    path('notifications/', include('notifications.urls', namespace='notifications')),
    path('notifications/clear_all/', views.clear_all_notifications, name='clear_all_notifications'),
    path('notifications/<int:notification_id>/clear/', views.clear_notification, name='clear_notification'),

    path('search_game/<str:game_name>/', views.search_game_on_steam, name='search_game_on_steam'),
    path('accounts/', include('allauth.urls')),
    
    path('view-events/', ViewEvents, name='events'),
    path('this-event/<int:event_id>', EventDetail, name='event-detail'),
    path('attend-event/<int:event_id>', attend_event, name='attend'),
    path('my_event/<int:pk>', MyEventUpdateView.as_view(), name='my_event'),
]

urlpatterns += steam_urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Testudo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('Main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('notifications/', include('notifications.urls')),

]

Main/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.auth.models import User

# Create your models here.

class Account(models.Model):
    #username and email are here to tie object back to user model for later
    user_owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    username = models.CharField(max_length=128, null=True, unique=True)
    password = models.CharField(max_length=64, default = 'password')
    email = models.CharField(max_length=128)
    account_name = models.CharField(max_length=128)
    account_bio = models.TextField()
    reported_count = models.PositiveIntegerField(default=0)
    steam_id = models.CharField(max_length=20, blank=True, null=True)
    steam_name = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.username

class Tag(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


#yes this stuff is crazy, I got it from here for reference: https://simpleisbetterthancomplex.com/tutorial/2016/10/13/how-to-use-generic-relations.html
class Activity(models.Model):
    FAVORITE = 'F'
    LIKE = 'L'
    UP_VOTE = 'U'
    DOWN_VOTE = 'D'
    ACTIVITY_TYPES = (
        (FAVORITE, 'Favorite'),
        (LIKE, 'Like'),
        (UP_VOTE, 'Up Vote'),
        (DOWN_VOTE, 'Down Vote'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    activity_type = models.CharField(max_length=1, choices=ACTIVITY_TYPES)
    date = models.DateTimeField(auto_now_add=True)

    # Below the mandatory fields for generic relation
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()


class Post(models.Model):
    accountname = models.ForeignKey(Account, on_delete=models.CASCADE, null=True, blank=True)
    post_title = models.CharField(max_length=128)
    post_community = models.CharField(max_length=128)
    post_body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField("Tag", related_name="posts")
    votes = GenericRelation(Activity)
    reported_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.post_title

class Comment(models.Model):
    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey("Post", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.author} on '{self.post}'"
    




templates/MyAccount.html
{% extends "base.html" %}

{% block content %}

    <h1><title>{% if account_name %}{{ account_name }}{% else %}{{ account.account_name }}{% endif %}'s Account</title></h1>
    <h2>Edit Account</h2>
    
    <form method="post">  
      {% csrf_token %}
      
      <div class="mb-3">
        <label for="id_email" class="form-label"
          data-bs-toggle="tooltip" data-bs-placement="top"
          data-bs-title="Enter your email address.">
          Email address:
        </label>
        <input type="email" name="email" value="{{ user.email }}" maxlength="254" id="id_email" class="form-control">
      </div>

      <div class="mb-3">
        <label for="id_username" class="form-label"
          data-bs-toggle="tooltip" data-bs-placement="top"
          data-bs-title="Choose a unique username. 150 characters or fewer. Letters, digits and @/./+/-/_ only.">
          Username:
        </label>
        <input type="text" name="username" value="{{ user.username }}"maxlength="150" required id="id_username" class="form-control">
      </div>

      <div class="mb-3">
        <label for="id_account_bio" class="form-label"
          data-bs-toggle="tooltip" data-bs-placement="top"
          data-bs-title="Write a brief bio about yourself.">
          Account bio:
        </label>
        <textarea name="account_bio" cols="40" rows="10" required id="id_account_bio" class="form-control">{{ user.account_bio }}</textarea>
      </div>

      <input type="submit" value="Save" class="btn btn-primary">
    </form>  
    </div>

    <div align="center" class="mt-4">
        <a href="{% url 'steam_login' %}" class="btn btn-primary">Log in with Steam</a>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // Initialize Bootstrap tooltips
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
            tooltipTriggerList.map(function (tooltipTriggerEl) {
                return new bootstrap.Tooltip(tooltipTriggerEl);
            });
        });
    </script>

{% endblock %}

templates/MyEvent.html
{% extends "base.html" %}

{% block title %}My Event{% endblock %}

{% block content %}
    <h2>Editing Event</h2>
    <form method="post">
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="{{ form.post_title.id_for_label }}" class="form-label"
                data-bs-toggle="tooltip" data-bs-placement="top"
                data-bs-title="Enter the title of the event">
                {{ form.post_title.label }}
            </label>
            {{ form.post_title }}
        </div>

        <div class="mb-3">
            <label for="{{ form.post_location.id_for_label }}" class="form-label"
                data-bs-toggle="tooltip" data-bs-placement="top"
                data-bs-title="Specify the location of the event">
                {{ form.post_location.label }}
            </label>
            {{ form.post_location }}
        </div>

        <div class="mb-3">
            <label for="{{ form.post_date_and_time.id_for_label }}" class="form-label"
                data-bs-toggle="tooltip" data-bs-placement="top"
                data-bs-title="Indicate the date and time of the event">
                {{ form.post_date_and_time.label }}
            </label>
            {{ form.post_date_and_time }}
        </div>

        <div class="mb-3">
            <label for="{{ form.post_body.id_for_label }}" class="form-label"
                data-bs-toggle="tooltip" data-bs-placement="top"
                data-bs-title="Provide details about the event">
                {{ form.post_body.label }}
            </label>
            {{ form.post_body }}
        </div>

        <div class="mb-3">
            <label for="{{ form.event_status.id_for_label }}" class="form-label"
                data-bs-toggle="tooltip" data-bs-placement="top"
                data-bs-title="Select the current status of the event">
                {{ form.event_status.label }}
            </label>
            {{ form.event_status }}
        </div>

        <input type="submit" value="Save" class="btn btn-primary">
    </form>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'));
            tooltipTriggerList.map(function (tooltipTriggerEl) {
                return new bootstrap.Tooltip(tooltipTriggerEl);
            });
        });
    </script>
{% endblock %}

templates/account_removed.html
<!doctype html>
<html lang="en">

  <body>
    <h3>Account Removed Successfully</h3>
    <a href="{% url 'home' %}">
      <button type="button" class="btn btn-dark">Return To Home</button>
    </a>
  </body>
</html>

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
      <a class="navbar-brand me-4" href="{% url 'home'%}">Sonar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'post_index' %}">Create Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'league_list' %}">Leagues</a>
          </li>
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'my_account' user.pk %}">My Account</a>
              <a class="nav-link" href="{% url 'register_business' %}">Register Business</a>
              <a class="nav-link" href="{% url 'discounts' %}">Browse Discounts</a>
              <a class="nav-link" href="{% url 'events' %}">See Events</a>
            {% else %}
                <a class="nav-link" href="{% url 'home' %}">Not Logged In</a>
            {% endif %}
          <li class="nav-item">
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
            {% endif %}
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'notifications_list' %}">Notifications</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

<style>
    body {
        background-color: #004385; 
        color: #FFFFFF;
    }
</style>

templates/create_account.html
{% extends "base.html" %}

{% block title %}Create Account{% endblock %}

{% block content %}
<body>
    <h1>Create Account</h1>
    <form method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
        <label for="email">Email:</label>
        <input type="text" id="email" name="email" required>
        <label for="account_name">Name:</label>
        <input type="text" id="account_name" name="account_name" required>
        <label for="account_bio">Bio:</label>
        <textarea id="account_bio" name="account_bio"></textarea>
        <button type="submit">Create Account</button>
    </form>
</body>
{% endblock %}

templates/event_detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}

{% block page_title %}
    <a href="{% url 'home' %}">
        <button type="button" class="btn btn-dark">Back to Home</button>
    </a>

    <h2 id="EventTitle">{{ event.post_title }}</h2>

    <p>
        On {{ event.created_on.date }} <b>{{ event.author }}</b> posted
    </p>
    
    <p>
        {{ event.post_location }}
    </p>
    <p>
        {{ event.post_date_and_time }}
    </p>
    <p>
        {{ event.event_status }}
    </p>
    <p>
        {{ event.post_body | linebreaks }}
    </p>

    <p>
        There are {{ num_of_people }} attending
    </p>

    <a href="{% url 'attend' event.pk %}">
        <button>Register</button>
    </a>

    {% if author %}

        <a href="{% url 'my_event' event.pk %}">
            <button>Edit Event</button>
        </a>

    {% endif %}

{% endblock page_title %}

{% block page_content %}
    
{% endblock page_content %}

{% endblock %}

templates/game_not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Game Not Found</title>
</head>
<body>
    <h1>Game Not Found</h1>
    <p>Sorry, we couldn't find the game "{{ game_name }}" on Steam.</p>
    <a href="/">Go back</a>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}

<p>Hi {{ user.username }}!</p>
<form action="{% url 'logout' %}" method="post">
  {% csrf_token %}
  <button type="submit">Log Out</button>
</form>

{% else %}






<div align="center">
  <div>
    <h1 style="font-size:100px;"> Sonar </h1>
  </div>

  <div style="display: flex; justify-content: center;">
    <a href="{% url 'login' %}">
      <button type="submit" class="btn btn-dark">Log In</button>
    </a>
    
    
    
    
    <a href="{% url 'sign_up' %}">
      <button type="submit" class="btn btn-secondary">Sign Up</button>
    </a>
    </div>

  <div style="margin-top: 50px;">
    <h3 style="margin-bottom: 50px;"> Hello, and welcome to Sonar. Sonar is an online event-hosting and networking platform to help you find, connect and have fun with those with similar interests.
      Have you ever wanted to connect with someone who plays the same games as you or has read the same books? Well you've come to the right place!
    </h3>

    <h3 style="margin-bottom: 50px;">
      In our ever connected world we find ourselves ever more apart. We send messages to friends everday, but when was the last time you had a meet up friends or made new ones?
      With Sonar, you can find new friends to build a Minecraft castle with, talk about your favorite book or even play a casual baseball game with. The possbilities are endless!
    </h3>

    <h3 style="margin-bottom: 50px;">
      Sonar has a suite of features like Leagues for sports and game tournaments, Steam integration to help verify and connect with others, event hosting facilities, special discount offers
      and so much more! There's nothing to lose but your boredom, sign up today!
    </h3>

  </div>


</div>







{% endif %}
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

{% block page_title %}
    <h2>Posts</h2>
{% endblock page_title %}

<style>
    .post-container {
        background-color: RoyalBlue;
        border-color: white;
        border-width: thin;
        border-style: double;
        padding: 10px;
        margin: 10px 0;
        color: white;
        text-align: center;
        
    }

    /* removes the hyperlink styling (ie the underline and blue text) */
    .post-container h3 a {
        color: white;
        text-decoration: none;
    }

</style>

<a href="{% url 'home' %}">
    <button type="button" class="btn btn-dark">Back to Home</button>
</a>

<form action="{% url 'search_results'%}" method="get">
    <input name="q" type="text" placeholder="Search...">
</form>

{% block page_content %}
    {% block posts %}
        <h3>New Post:</h3>
        <div id="tagForm" style="margin-bottom: 50px;">
            <form method="post">
                {% csrf_token %}
                <div>
                    {{ form.post_title }}
                </div>
                <div>
                    {{ form.post_community }}
                </div>
                <div>
                    {{ form.post_body }}
                </div>
                <!-- Add the tags input field with id="tagInput" -->
                <div>
                    <label for="tagInput">Tags:</label>
                    <input type="text" name="tags" id="tagInput" placeholder="Tags" autocomplete="off">
                </div>
                <!-- Add a submit button -->
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div align="center" style="overflow-y: scroll;">
        {% for post in posts %}
        

        <div align="center"  class="post-container">
            <h3><a href="{% url 'post_detail' post.pk 0 %}">{{ post.post_title }}</a></h3>
            <h4>
                {{ post.created_on.date }} | 
                {% if post.accountname %}
                    <a href="{% url 'user_account' post.accountname.pk %}" style="text-decoration: none;color: white;">
                        {{ post.accountname.username }}
                    </a>
                {% else %}
                    <p> ERROR: No account found </p>
                {% endif %}
                
                {% if post.tags.all %}
                | Tags:
                {% endif %}

                {% for tag in post.tags.all %}

                    <a href="{% url 'post_tag' tag.name %}" style="text-decoration: none;color:white;">
                        {{ tag.name }}
                    </a>
                {% endfor %}
                </h4>
            <p>{{ post.post_body | slice:":400" }}...</p>
        </div>

        {% endfor %}
    </div>
    {% endblock posts %}
{% endblock page_content %}

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var tagInput = document.getElementById('tagInput');
        var postForm = document.getElementById('postForm');

        tagInput.addEventListener('keypress', function(event) {
            if (event.key === 'Enter') {
                // Prevent default behavior of Enter key
                event.preventDefault();

                // Get the current caret position
                var caretPosition = tagInput.selectionStart;
                
                // Insert a comma at the caret position
                var value = tagInput.value;
                tagInput.value = value.slice(0, caretPosition) + ',' + value.slice(caretPosition);

                // Move the caret to the position after the comma
                tagInput.selectionStart = tagInput.selectionEnd = caretPosition + 1;
            }
        });

        postForm.addEventListener('submit', function(event) {
            // Prevent form submission
            event.preventDefault();
            // Add your form submission handling code here if needed
        });
    });
</script>

{% endblock %}

templates/profile_pic.html
<!DOCTYPE html>
<html>
<head>
    <title>Profile Picture</title>
</head>
<body>
    <h1>Upload Profile Picture</h1>

    {% if user.profile_picture %}
        <img src="{{ user.profile_picture.url }}" alt="Profile Picture" width="150" height="150">
    {% else %}
        <p>No profile picture available.</p>
    {% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
</body>
</html>

templates/register.html
{% extends "base.html" %}   
{% block content %}  
<div class = "login">  
      
   
          
    <h1>Register Here</h1>  
      
         <form method="post" >  
             {% csrf_token %}  
             <table>  
                {{ form.as_table }}  
                 <tr>  
                    <td></td>  
                    <td><button type="submit" class="btn btn-dark">Register</button></td>  
                </tr>  
             </table>  
         </form>  
     </div>  
{% endblock %}

templates/register_business.html
{% extends "base.html" %}
{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Register Business</title>
</head>
<body>
    <a href="{% url 'home' %}">
        <button type="button" class="btn btn-dark">Back to Home</button>
    </a>

    <h1>Register Business</h1>

    <h4> If you are the owner or chosen representative of a registered Canadian business you can associate it with your account by entering the corporation's valid business number below.
        The Sonar team will review your application with assistance from the Government of Canada's Federal Corporation API from the ISED API Catalogue. Once this process has been completed
        successfully, you will be able to post discounts and special offers on behalf of your business to the Sonar community. The fact that you have a business associated with your account
        will also be public to other Sonar users when viewing your account. Thank you for choosing the Sonar platform for your business needs.
    </h4>
    <div align="center" style="margin-top: 50px;">
    <form method="post">
        {% csrf_token %}
        <input type="text" name="business_number">
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>


    {% if error %}
        <p> Sorry, we couldn't find that business or it's already registered. Please try again. </p>
    {% endif %}
    </div>
</body>
</html>
{% endblock %}

templates/search_account.html
{% extends "base.html" %}   
{% block content %}  
<!DOCTYPE html>
<html>
<head>
    <title>Search Accounts</title>
</head>
<body>
    <a href="{% url 'home' %}">
        <button type="button" class="btn btn-dark">Back to Home</button>
    </a>

    <h1>Search Accounts</h1>
    <form method="get">
        <input type="text" name="q" placeholder="Search accounts..." value="{{ query }}">
        <button type="submit">Search</button>
    </form>
    
        {% for user in users %}
        <div align="center" style="background-color: RoyalBlue; border-color: white; border-width: thin; border-style: double;">
            <h4>{{ user.username }}</h4>
            <p>{{ user.account.bio }}</p>
        </div>
        
        {% empty %}
        <h3>No users found</h3>
        {% endfor %}
    
</body>
</html>
{% endblock %}

templates/view_discounts.html
{% extends "base.html" %}

{% block content %}

<!DOCTYPE html>
<html>
  
<style>

      .discount-container {
          background-color: RoyalBlue;
          padding: 10px;
          margin: 10px 0;
          color: white;
          text-align: center;
          
      }
    
</style>
  
<head>
    <a href="{% url 'home' %}">
        <button type="button" class="btn btn-dark">Back to Home</button>
        </a>
    <title>Discount Offers</title>
</head>
<body>
    <h1>Current Special Offers</h1>

    <div align="center">
        <h4> This is where businesses and organizations post special offers and discounts for Sonar users. You must have a registered business associated with your account to post here, but anyone can use the offers posted. New offers are always on the way, so make sure to check back often!</h4>
    </div>

    

    {% if is_business %}

    <h3>Create an offer:</h3>
    <form method="post">
        {% csrf_token %}
        
        <div>
            {{ form.body }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    {% endif %}

    <h3>Current Offers:</h3>

    {% if offers %}
    <div align="center" style="overflow-y: scroll;">
    {% for offer in offers %}
        <div class="discount-container">
            <p>
                On {{ offer.created_on.date }} <b>{{ offer.author }}</b>
            </p>
            <p>
                {{ offer.body | linebreaks }}
            </p>
        </div>
    {% endfor %}
    </div>

    {% else %}

    <h4>There aren't any offers yet. Don't worry, good things are worth the wait.</h4>

    {% endif %}



    

    
    
</body>
</html>

{% endblock %}